# Generated by Django 3.1.5 on 2021-01-12 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(3, '세 글자 이상 입력해주세요.'), django.core.validators.RegexValidator('^[가-힣a-zA-Z]+$', '알파벳과 한글(단일 자음 모음 불가)로 작성해주세요.')], verbose_name='닉네임'),
        ),
    ]
