# Generated by Django 3.1.5 on 2021-01-13 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20210112_2216'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(3, '세 글자 이상 입력해주세요.'), django.core.validators.RegexValidator('^[가-힣a-zA-Z]+$', '알파벳과 한글로 작성해주세요. (단일 자음 모음 및 공백 불가)')], verbose_name='닉네임'),
        ),
    ]
