# Generated by Django 3.1.4 on 2021-01-19 17:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to='worldcupapp/album/thumbnail/%Y/%m/%d/', verbose_name='썸네일')),
            ],
        ),
        migrations.CreateModel(
            name='CommentBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시각')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시각')),
                ('title', models.CharField(max_length=31, verbose_name='제목')),
                ('win_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='월드컵 승리 횟수')),
                ('choice_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='1:1 승리 횟수')),
                ('media', models.FileField(upload_to='worldcupapp/image/%Y/%m/%d/%h', verbose_name='이미지 파일')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pikuapp.album')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시각')),
                ('title', models.CharField(max_length=31, verbose_name='제목')),
                ('win_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='월드컵 승리 횟수')),
                ('choice_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='1:1 승리 횟수')),
                ('media', models.TextField(max_length=511, verbose_name='텍스트')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pikuapp.album')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worldcup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시각')),
                ('title', models.CharField(max_length=63, verbose_name='제목')),
                ('intro', models.CharField(max_length=255, verbose_name='소개')),
                ('publish_type', models.CharField(choices=[('A', '전체 공개'), ('P', '암호 공개'), ('N', '비공개')], default='N', max_length=1, verbose_name='배포 방식')),
                ('media_type', models.CharField(choices=[('T', '텍스트'), ('I', '이미지')], default='I', max_length=1, verbose_name='미디어 타입')),
                ('password', models.CharField(blank=True, max_length=31, validators=[django.core.validators.MinLengthValidator(3, '세 글자 이상의 암호를 설정해주세요.')], verbose_name='암호')),
                ('play_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='플레이 횟수')),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pikuapp.album', verbose_name='미디어')),
                ('comment_board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pikuapp.commentboard', verbose_name='댓글')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=511, verbose_name='댓글 내용')),
                ('comment_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pikuapp.commentboard')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pikuapp.text', verbose_name='텍스트 미디어')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('worldcup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pikuapp.worldcup', verbose_name='월드컵')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=511, verbose_name='댓글 내용')),
                ('comment_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pikuapp.commentboard')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pikuapp.image', verbose_name='이미지 미디어')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('worldcup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pikuapp.worldcup', verbose_name='월드컵')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
