# Generated by Django 3.1.4 on 2021-01-20 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pikuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentboard',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='commentboard',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='imagecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성시각'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정시각'),
        ),
        migrations.AddField(
            model_name='textcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성시각'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정시각'),
        ),
    ]
