# Generated by Django 3.1.4 on 2021-01-22 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pikuapp', '0002_auto_20210120_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시각')),
                ('media_id', models.PositiveIntegerField(blank=True, verbose_name='신고된 미디어 id')),
                ('category', models.TextField(choices=[('음란물', '음란물을 게시하였습니다.'), ('기타', '기타')], verbose_name='신고 사유')),
                ('contents', models.TextField(blank=True, max_length=255, verbose_name='신고 내용')),
                ('reporter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
                ('worldcup', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pikuapp.worldcup', verbose_name='신고된 미디어가 포함된 월드컵')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시각')),
                ('comment_id', models.PositiveIntegerField(blank=True, verbose_name='신고된 댓글 id')),
                ('category', models.TextField(choices=[('욕설', '해당 댓글에 욕설이 포함되어 있습니다.'), ('기타', '기타')], verbose_name='신고 사유')),
                ('contents', models.TextField(blank=True, max_length=255, verbose_name='신고 내용')),
                ('reporter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
                ('worldcup', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pikuapp.worldcup', verbose_name='신고된 댓글이 포함된 월드컵')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
