# Generated by Django 3.1.5 on 2021-01-15 12:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('T', 'text'), ('I', 'image'), ('G', 'gif'), ('V', 'video')], default=None, max_length=1, verbose_name='데이터 타입')),
                ('thumbnail', models.ImageField(editable=False, upload_to='worldcupapp/album/thumbnail/%Y/%m/%d/', verbose_name='썸네일')),
            ],
        ),
        migrations.CreateModel(
            name='Worldcup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='제목')),
                ('intro', models.CharField(max_length=255, verbose_name='소개')),
                ('publish_type', models.CharField(choices=[('A', 'All, 전체공개'), ('P', 'Password, 암호'), ('N', 'Not Publish, 비공개')], default='N', max_length=1, verbose_name='배포 방식')),
                ('password', models.CharField(blank=True, max_length=31, validators=[django.core.validators.MinLengthValidator(1, '최소 한 글자 이상의 암호를 설정해주세요.')], verbose_name='암호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('play_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='플레이 횟수')),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='worldcupapp.album', verbose_name='앨범')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=511, verbose_name='외부 비디오 링크')),
                ('win_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='월드컵 승리 횟수')),
                ('choice_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='1:1 승리 횟수')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_set', to='worldcupapp.album')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=511, verbose_name='텍스트')),
                ('win_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='월드컵 승리 횟수')),
                ('choice_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='1:1 승리 횟수')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_set', to='worldcupapp.album')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='worldcupapp/image/%Y/%m/%d/%h', verbose_name='이미지 파일')),
                ('win_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='월드컵 승리 횟수')),
                ('choice_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='1:1 승리 횟수')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='worldcupapp.album')),
            ],
        ),
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='worldcupapp/gif/%Y/%m/%d/%h', verbose_name='움짤 파일 (gif -> mp4)')),
                ('win_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='월드컵 승리 횟수')),
                ('choice_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='1:1 승리 횟수')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gif_set', to='worldcupapp.album')),
            ],
        ),
    ]
